openapi: 3.0.0
info:
  title: Finic AI API
  version: 1.0.0
  description: API for running Finic AI agents

servers:
  - url: https://api.finic.ai

paths:
  /run-agent:
    post:
      summary: Run an agent
      description: Execute a specific AI agent with given input
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                agent_id:
                  type: string
                  description: The ID of the agent to run, defined when you first deployed the agent.
                input:
                  type: object
                  description: The input data for the agent. Each field will be passed as an argument to the agent's entrypoint function.
              required:
                - agent_id
      responses:
        '200':
          description: Successful response. Agent has started running.
          content:
            application/json:
              schema:
                type: object
                # You can define the response structure here if known
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer